# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GF', '0003_auto_20170113_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GF.Comment'),
        ),
    ]
