# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GF', '0004_auto_20170113_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='article_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='GF.Article'),
        ),
    ]
