# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GF', '0008_auto_20170113_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('edit_own_article', 'Can edit his own the article'),)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('edit_own_comment', 'Can edit his own comment'),)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='color',
        ),
        migrations.AlterField(
            model_name='comment',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GF.Article'),
        ),
    ]
