# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GF', '0009_auto_20170114_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specs',
            name='article',
        ),
        migrations.DeleteModel(
            name='Specs',
        ),
    ]
